-- MOL L5IBRA database starter
create table if not exists public.content (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('news','legend','product')),
  title text not null,
  text text,
  tag text,
  price text,
  created_at timestamptz default now()
);

alter table public.content enable row level security;

-- Public website can read published content.
create policy "Public can read content"
on public.content for select
to anon, authenticated
using (true);

-- For a real admin system, create an Auth user in Supabase
-- and replace the policy below with an authenticated/admin role policy.
-- Do NOT make insert/update/delete public.

insert into public.content(type,title,text,tag,price) values
('news','Welcome to MOL L5IBRA','Your new home for football stories, wisdom and legends.','FOOTBALL',null),
('legend','The Legends','Build your own collection of unforgettable players.','LEGEND',null),
('product','MOL L5IBRA T-Shirt','Store demo product.','STORE','—');